import { LensCard } from '@/components/LensCard';
import { SearchBox } from '@/components/SearchBox';
import { createLensSnapshot, getSeedTrending } from '@/lib/lens-service';
import Link from 'next/link';

export default async function SearchPage({ searchParams }: { searchParams: { q?: string } }) {
  const query = searchParams.q ?? '';
  let results = getSeedTrending();
  let isLive = false;
  let error = '';

  if (query.trim()) {
    try {
      results = [await createLensSnapshot(query)];
      isLive = true;
    } catch (err) {
      results = [];
      error = err instanceof Error ? err.message : 'Search failed.';
    }
  }

  return (
    <main className="mx-auto min-h-screen max-w-6xl px-6 py-10">
      <Link href="/" className="text-sm font-medium text-slate-500 hover:text-slate-900 transition-colors">← Back</Link>

      <div className="mt-6">
        <SearchBox initialValue={query} />
      </div>

      {query && (
        <div className="mt-8">
          <div className="flex items-center gap-3">
            <h1 className="text-3xl font-bold">{query}</h1>
            {isLive && (
              <span className="rounded-full bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 text-xs font-semibold text-emerald-700">
                Live Lens™
              </span>
            )}
          </div>
          <p className="mt-1 text-sm text-slate-500">Lens Snapshot™ generated by Transformation Intelligence™</p>
        </div>
      )}

      {!query && (
        <div className="mt-8">
          <h1 className="text-3xl font-bold">Explore The Lens™</h1>
          <p className="mt-1 text-sm text-slate-500">Browse trending Lens Cards™ or search any company, industry, or idea.</p>
        </div>
      )}

      {error && (
        <div className="card mt-8 p-8">
          <h2 className="text-lg font-semibold text-slate-900">Lens configuration needed</h2>
          <p className="mt-2 text-sm text-slate-600">{error}</p>
          <p className="mt-4 text-sm text-slate-500">
            Add <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">ANTHROPIC_API_KEY</code> or{' '}
            <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">OPENAI_API_KEY</code> to <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">.env.local</code> to enable live Lens generation.
          </p>
        </div>
      )}

      {results.length > 0 && (
        <div className="mt-8 grid gap-5 lg:grid-cols-3">
          {results.map((item) => <LensCard key={item.id} item={item} />)}
        </div>
      )}

      {results.length === 0 && !error && (
        <div className="card mt-8 p-8 text-center">
          <h2 className="text-xl font-semibold">No Lens Card found.</h2>
          <p className="mt-2 text-slate-600">Try a different search term or configure an AI provider.</p>
        </div>
      )}
    </main>
  );
}
